In [ ]:
# exp 15
# riya latkar
# 25070123092
# aim: Data normalisatin and data type conversion

import pandas as pd
import numpy as np

data = {
    'Product': ['Laptop', 'Mobile', 'Tablet', 'Headphones', 'Smartwatch', 'Camera'],
    'Price': [55000, 20000, 30000, 2000, 8000, 45000],
    'Units_Sold': [25, 60, 35, 80, 50, 15],
    'Discount': [10, 5, 15, 0, 10, 20]
}

df = pd.DataFrame(data)
display(df, "\n")

      Product  Price  Units_Sold  Discount
0      Laptop  55000          25        10
1      Mobile  20000          60         5
2      Tablet  30000          35        15
3  Headphones   2000          80         0
4  Smartwatch   8000          50        10
5      Camera  45000          15        20

'\n'

In [ ]:
## 1. min max normalisaton
#min max normalisation for price
df["Price_MinMax"] = (df["Price"] - df["Price"].min()) / (df["Price"].max() - df["Price"].min())
display(df[['Product', 'Price', 'Price_MinMax']] )

#min max normalisation for discount
df["Discount_MinMax"] = (df["Discount"] - df["Discount"].min()) / (df["Discount"].max() - df["Discount"].min())
display(df[['Product', 'Discount', 'Discount_MinMax']] )

#min max normalisation for units sold
df["Units_Sold_MinMax"] = (df["Units_Sold"] - df["Units_Sold"].min()) / (df["Units_Sold"].max() - df["Units_Sold"].min())
display(df[['Product', 'Units_Sold', 'Units_Sold_MinMax']])

      Product  Price  Price_MinMax
0      Laptop  55000      1.000000
1      Mobile  20000      0.339623
2      Tablet  30000      0.528302
3  Headphones   2000      0.000000
4  Smartwatch   8000      0.113208
5      Camera  45000      0.811321

      Product  Discount  Discount_MinMax
0      Laptop        10             0.50
1      Mobile         5             0.25
2      Tablet        15             0.75
3  Headphones         0             0.00
4  Smartwatch        10             0.50
5      Camera        20             1.00

      Product  Units_Sold  Units_Sold_MinMax
0      Laptop          25           0.153846
1      Mobile          60           0.692308
2      Tablet          35           0.307692
3  Headphones          80           1.000000
4  Smartwatch          50           0.538462
5      Camera          15           0.000000

In [ ]:
# Normalise Multiple Columns
cols = ["Price", "Units_Sold", "Discount"]
df_norm = (df[cols]- df[cols].min()) / (df[cols].max() - df[cols].min())
display(df_norm)

      Price  Units_Sold  Discount
0  1.000000    0.153846      0.50
1  0.339623    0.692308      0.25
2  0.528302    0.307692      0.75
3  0.000000    1.000000      0.00
4  0.113208    0.538462      0.50
5  0.811321    0.000000      1.00

In [ ]:
## 2. Z-score optimisation
df["Units_Zscore"] = (df["Units_Sold"] - df["Units_Sold"].mean())/ df["Units_Sold"].std()
display(df[['Product', 'Units_Sold', 'Units_Zscore']])

      Product  Units_Sold  Units_Zscore
0      Laptop          25     -0.799885
1      Mobile          60      0.660775
2      Tablet          35     -0.382554
3  Headphones          80      1.495437
4  Smartwatch          50      0.243443
5      Camera          15     -1.217216

In [ ]:
## 3. Decimal Scaling
df["Units_Sold_Scaled"] = df["Units_Sold"] / 100
df["Discount_Scaled"]= df["Discount"] / 100
display(df[['Product', 'Units_Sold', 'Units_Sold_Scaled', 'Discount_Scaled']])

      Product  Units_Sold  Units_Sold_Scaled  Discount_Scaled
0      Laptop          25               0.25             0.10
1      Mobile          60               0.60             0.05
2      Tablet          35               0.35             0.15
3  Headphones          80               0.80             0.00
4  Smartwatch          50               0.50             0.10
5      Camera          15               0.15             0.20

In [ ]:
import pandas as pd
import numpy as np
data = {
'Order_ID':[101,102,103,104,105,106],
'Customer_Gender':['Male','Female','Female','Male','Female','Male'],
'Payment_Method':['UPI','Credit Card','Debit Card','COD','UPI','Debit Card'],
'Product_Category':['Electronics','Clothing','Home','Electronics','Beauty','Electronics'],
'City':['Pune','Mumbai','Delhi','Bangalore','Pune','Hyderabad'],
'Order_Value':[4500,2300,3200,5200,1800,4100]
}
df = pd.DataFrame(data)
display(df)

,Order_ID,Customer_Gender,Payment_Method,Product_Category,City,Order_Value
0,101,Male,UPI,Electronics,Pune,4500
1,102,Female,Credit Card,Clothing,Mumbai,2300
2,103,Female,Debit Card,Home,Delhi,3200
3,104,Male,COD,Electronics,Bangalore,5200
4,105,Female,UPI,Beauty,Pune,1800
5,106,Male,Debit Card,Electronics,Hyderabad,4100

In [ ]:
# Method 1: Label encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Customer_Gender_Label'] = le.fit_transform(df['Customer_Gender'])
#df['Payment_Method_Label'] = le.fit_transform(df['Payment_Method'])
#df['Product_Category_Label'] = le.fit_transform(df['Product_Category])
df['City_Label'] = le.fit_transform(df['City'])
display(df)

,Order_ID,Customer_Gender,Payment_Method,Product_Category,City,Order_Value,Customer_Gender_Label,City_Label
0,101,Male,UPI,Electronics,Pune,4500,1,4
1,102,Female,Credit Card,Clothing,Mumbai,2300,0,3
2,103,Female,Debit Card,Home,Delhi,3200,0,1
3,104,Male,COD,Electronics,Bangalore,5200,1,0
4,105,Female,UPI,Beauty,Pune,1800,0,4
5,106,Male,Debit Card,Electronics,Hyderabad,4100,1,2

In [ ]:
#Method 2 : One-Hot encoding
df_encoded = pd.get_dummies(df, columns=['Payment_Method', 'Product_Category', 'City'])
display(df_encoded)

,Order_ID,Customer_Gender,Order_Value,Customer_Gender_Label,City_Label,Payment_Method_COD,Payment_Method_Credit Card,Payment_Method_Debit Card,Payment_Method_UPI,Product_Category_Beauty,Product_Category_Clothing,Product_Category_Electronics,Product_Category_Home,City_Bangalore,City_Delhi,City_Hyderabad,City_Mumbai,City_Pune
0,101,Male,4500,1,4,False,False,False,True,False,False,True,False,False,False,False,False,True
1,102,Female,2300,0,3,False,True,False,False,False,True,False,False,False,False,False,True,False
2,103,Female,3200,0,1,False,False,True,False,False,False,False,True,False,True,False,False,False
3,104,Male,5200,1,0,True,False,False,False,False,False,True,False,True,False,False,False,False
4,105,Female,1800,0,4,False,False,False,True,True,False,False,False,False,False,False,False,True
5,106,Male,4100,1,2,False,False,True,False,False,False,True,False,False,False,True,False,False

In [ ]:
# Encoded Multiple Columns
cols = ['Product_Category', 'City']
df_multi = pd.get_dummies(df, columns=cols)
display(df_multi)

,Order_ID,Customer_Gender,Payment_Method,Order_Value,Customer_Gender_Label,City_Label,Product_Category_Beauty,Product_Category_Clothing,Product_Category_Electronics,Product_Category_Home,City_Bangalore,City_Delhi,City_Hyderabad,City_Mumbai,City_Pune
0,101,Male,UPI,4500,1,4,False,False,True,False,False,False,False,False,True
1,102,Female,Credit Card,2300,0,3,False,True,False,False,False,False,False,True,False
2,103,Female,Debit Card,3200,0,1,False,False,False,True,False,True,False,False,False
3,104,Male,COD,5200,1,0,False,False,True,False,True,False,False,False,False
4,105,Female,UPI,1800,0,4,True,False,False,False,False,False,False,False,True
5,106,Male,Debit Card,4100,1,2,False,False,True,False,False,False,True,False,False

In [ ]:
# Method 3: Dummy Encoding (Drop First)
df_dummy = pd.get_dummies(df, columns=['Payment_Method'], drop_first=True)
display(df_dummy)

,Order_ID,Customer_Gender,Product_Category,City,Order_Value,Customer_Gender_Label,City_Label,Payment_Method_Credit Card,Payment_Method_Debit Card,Payment_Method_UPI
0,101,Male,Electronics,Pune,4500,1,4,False,False,True
1,102,Female,Clothing,Mumbai,2300,0,3,True,False,False
2,103,Female,Home,Delhi,3200,0,1,False,True,False
3,104,Male,Electronics,Bangalore,5200,1,0,False,False,False
4,105,Female,Beauty,Pune,1800,0,4,False,False,True
5,106,Male,Electronics,Hyderabad,4100,1,2,False,True,False

In [ ]:
# Data Normalisation
import pandas as pd
df = pd.read_csv("amazon_products_dataset_Expt-14.csv")
display(df)

   Product_ID                 Product_Name  Price  Rating  Reviews  Units_Sold
0        P101               Wireless Mouse    799     4.3     1520         350
1        P102            Bluetooth Speaker   1499     4.5      980         220
2        P103                 USB Keyboard    699     4.1      870         180
3        P104               Gaming Headset   2499     4.6     2100         410
4        P105                   Smartwatch   3999     4.4     3050         520
5        P106                   Power Bank   1199     4.2     1750         390
6        P107                 Laptop Stand    899     4.0      620         140
7        P108                       Webcam   1899     4.3     1120         260
8        P109                 Portable SSD   5499     4.7     1850         330
9        P110             Wireless Charger    999     4.2      760         190
10       P111  Noise Cancelling Headphones   7999     4.6     4200         610
11       P112          Mechanical Keyboard   4599     4.5     2100         290
12       P113                 Gaming Mouse   1599     4.4     1300         340
13       P114                 Tablet Stand    699     4.1      540         120
14       P115                      USB Hub    899     4.2      870         200
15       P116          External Hard Drive   6499     4.6     2300         310
16       P117            Smartphone Tripod   1199     4.3      760         210
17       P118              Laptop Backpack   1999     4.4     1600         420
18       P119            Bluetooth Earbuds   2999     4.5     3500         530
19       P120                LED Desk Lamp   1299     4.3      980         260
20       P121                 Phone Holder    499     4.0      420         150
21       P122            Wireless Keyboard   2499     4.4     1450         310
22       P123             Portable Monitor   8999     4.6     1250         170
23       P124                   Smart Plug    799     4.2      720         210
24       P125                  WiFi Router   3499     4.5     2100         390
25       P126              Graphics Tablet   4599     4.4      980         160
26       P127                   VR Headset  12999     4.7     3100         140
27       P128                   Microphone   2199     4.3     1300         270
28       P129             Smart Light Bulb    699     4.2      880         240
29       P130           Laptop Cooling Pad   1499     4.3      990         260
30       P131                Action Camera   9999     4.6     2100         200
31       P132               Smart Doorbell   5999     4.5     1750         180
32       P133              Streaming Stick   3499     4.4     2500         430
33       P134           Portable Projector  11999     4.6     1450         120
34       P135                 Gaming Chair  15999     4.7     2100          90
35       P136               Desk Organizer    599     4.1      450         160
36       P137              USB Flash Drive    799     4.2      900         320
37       P138       Phone Screen Protector    299     4.0      600         380
38       P139                Laptop Sleeve    999     4.3      720         210
39       P140           Wireless Presenter   1499     4.4      520         130
40       P141         Tablet Keyboard Case   2999     4.5      850         150
41       P142             Smart Thermostat  10999     4.6     1200         110
42       P143              Security Camera   4999     4.4     2100         260
43       P144                 Drone Camera  24999     4.7     1800          70
44       P145              Electric Kettle   1999     4.3     1400         310
45       P146                    Air Fryer   7999     4.6     2200         200
46       P147                 Robot Vacuum  18999     4.5     1650         120
47       P148                  Smart Scale   2499     4.4      980         170
48       P149          Digital Photo Frame   3499     4.3      870         150
49       P150                 Portable Fan    999     4.2      760         240

In [ ]:
# Min-Max Normalisation (all)
#min max normalisation for price
df["Price_MinMax"] = (df["Price"] - df["Price"].min()) / (df["Price"].max() - df["Price"].min())
display(df[['Product_Name', 'Price', 'Price_MinMax']] )
print("\n")

#min max normalisation for rating
df["Rating_MinMax"] = (df["Rating"] - df["Rating"].min()) / (df["Rating"].max() - df["Rating"].min())
display(df[['Product_Name', 'Rating', 'Rating_MinMax']] )
print("\n")

#min max normalisation for units sold
df["Units_Sold_MinMax"] = (df["Units_Sold"] - df["Units_Sold"].min()) / (df["Units_Sold"].max() - df["Units_Sold"].min())
display(df[['Product_Name', 'Units_Sold', 'Units_Sold_MinMax']])
print("\n")

                   Product_Name  Price  Price_MinMax
0                Wireless Mouse    799      0.020243
1             Bluetooth Speaker   1499      0.048583
2                  USB Keyboard    699      0.016194
3                Gaming Headset   2499      0.089069
4                    Smartwatch   3999      0.149798
5                    Power Bank   1199      0.036437
6                  Laptop Stand    899      0.024291
7                        Webcam   1899      0.064777
8                  Portable SSD   5499      0.210526
9              Wireless Charger    999      0.028340
10  Noise Cancelling Headphones   7999      0.311741
11          Mechanical Keyboard   4599      0.174089
12                 Gaming Mouse   1599      0.052632
13                 Tablet Stand    699      0.016194
14                      USB Hub    899      0.024291
15          External Hard Drive   6499      0.251012
16            Smartphone Tripod   1199      0.036437
17              Laptop Backpack   1999      0.068826
18            Bluetooth Earbuds   2999      0.109312
19                LED Desk Lamp   1299      0.040486
20                 Phone Holder    499      0.008097
21            Wireless Keyboard   2499      0.089069
22             Portable Monitor   8999      0.352227
23                   Smart Plug    799      0.020243
24                  WiFi Router   3499      0.129555
25              Graphics Tablet   4599      0.174089
26                   VR Headset  12999      0.514170
27                   Microphone   2199      0.076923
28             Smart Light Bulb    699      0.016194
29           Laptop Cooling Pad   1499      0.048583
30                Action Camera   9999      0.392713
31               Smart Doorbell   5999      0.230769
32              Streaming Stick   3499      0.129555
33           Portable Projector  11999      0.473684
34                 Gaming Chair  15999      0.635628
35               Desk Organizer    599      0.012146
36              USB Flash Drive    799      0.020243
37       Phone Screen Protector    299      0.000000
38                Laptop Sleeve    999      0.028340
39           Wireless Presenter   1499      0.048583
40         Tablet Keyboard Case   2999      0.109312
41             Smart Thermostat  10999      0.433198
42              Security Camera   4999      0.190283
43                 Drone Camera  24999      1.000000
44              Electric Kettle   1999      0.068826
45                    Air Fryer   7999      0.311741
46                 Robot Vacuum  18999      0.757085
47                  Smart Scale   2499      0.089069
48          Digital Photo Frame   3499      0.129555
49                 Portable Fan    999      0.028340

                   Product_Name  Rating  Rating_MinMax
0                Wireless Mouse     4.3       0.428571
1             Bluetooth Speaker     4.5       0.714286
2                  USB Keyboard     4.1       0.142857
3                Gaming Headset     4.6       0.857143
4                    Smartwatch     4.4       0.571429
5                    Power Bank     4.2       0.285714
6                  Laptop Stand     4.0       0.000000
7                        Webcam     4.3       0.428571
8                  Portable SSD     4.7       1.000000
9              Wireless Charger     4.2       0.285714
10  Noise Cancelling Headphones     4.6       0.857143
11          Mechanical Keyboard     4.5       0.714286
12                 Gaming Mouse     4.4       0.571429
13                 Tablet Stand     4.1       0.142857
14                      USB Hub     4.2       0.285714
15          External Hard Drive     4.6       0.857143
16            Smartphone Tripod     4.3       0.428571
17              Laptop Backpack     4.4       0.571429
18            Bluetooth Earbuds     4.5       0.714286
19                LED Desk Lamp     4.3       0.428571
20                 Phone Holder     4.0       0.000000
21            Wireless Keyboard     4.4       0.571429
22             Portable Monitor     4.6       0.857143
23                   Smart Plug     4.2       0.285714
24                  WiFi Router     4.5       0.714286
25              Graphics Tablet     4.4       0.571429
26                   VR Headset     4.7       1.000000
27                   Microphone     4.3       0.428571
28             Smart Light Bulb     4.2       0.285714
29           Laptop Cooling Pad     4.3       0.428571
30                Action Camera     4.6       0.857143
31               Smart Doorbell     4.5       0.714286
32              Streaming Stick     4.4       0.571429
33           Portable Projector     4.6       0.857143
34                 Gaming Chair     4.7       1.000000
35               Desk Organizer     4.1       0.142857
36              USB Flash Drive     4.2       0.285714
37       Phone Screen Protector     4.0       0.000000
38                Laptop Sleeve     4.3       0.428571
39           Wireless Presenter     4.4       0.571429
40         Tablet Keyboard Case     4.5       0.714286
41             Smart Thermostat     4.6       0.857143
42              Security Camera     4.4       0.571429
43                 Drone Camera     4.7       1.000000
44              Electric Kettle     4.3       0.428571
45                    Air Fryer     4.6       0.857143
46                 Robot Vacuum     4.5       0.714286
47                  Smart Scale     4.4       0.571429
48          Digital Photo Frame     4.3       0.428571
49                 Portable Fan     4.2       0.285714

                   Product_Name  Units_Sold  Units_Sold_MinMax
0                Wireless Mouse         350           0.518519
1             Bluetooth Speaker         220           0.277778
2                  USB Keyboard         180           0.203704
3                Gaming Headset         410           0.629630
4                    Smartwatch         520           0.833333
5                    Power Bank         390           0.592593
6                  Laptop Stand         140           0.129630
7                        Webcam         260           0.351852
8                  Portable SSD         330           0.481481
9              Wireless Charger         190           0.222222
10  Noise Cancelling Headphones         610           1.000000
11          Mechanical Keyboard         290           0.407407
12                 Gaming Mouse         340           0.500000
13                 Tablet Stand         120           0.092593
14                      USB Hub         200           0.240741
15          External Hard Drive         310           0.444444
16            Smartphone Tripod         210           0.259259
17              Laptop Backpack         420           0.648148
18            Bluetooth Earbuds         530           0.851852
19                LED Desk Lamp         260           0.351852
20                 Phone Holder         150           0.148148
21            Wireless Keyboard         310           0.444444
22             Portable Monitor         170           0.185185
23                   Smart Plug         210           0.259259
24                  WiFi Router         390           0.592593
25              Graphics Tablet         160           0.166667
26                   VR Headset         140           0.129630
27                   Microphone         270           0.370370
28             Smart Light Bulb         240           0.314815
29           Laptop Cooling Pad         260           0.351852
30                Action Camera         200           0.240741
31               Smart Doorbell         180           0.203704
32              Streaming Stick         430           0.666667
33           Portable Projector         120           0.092593
34                 Gaming Chair          90           0.037037
35               Desk Organizer         160           0.166667
36              USB Flash Drive         320           0.462963
37       Phone Screen Protector         380           0.574074
38                Laptop Sleeve         210           0.259259
39           Wireless Presenter         130           0.111111
40         Tablet Keyboard Case         150           0.148148
41             Smart Thermostat         110           0.074074
42              Security Camera         260           0.351852
43                 Drone Camera          70           0.000000
44              Electric Kettle         310           0.444444
45                    Air Fryer         200           0.240741
46                 Robot Vacuum         120           0.092593
47                  Smart Scale         170           0.185185
48          Digital Photo Frame         150           0.148148
49                 Portable Fan         240           0.314815

In [ ]:
#Normalising multiple columns
cols = ["Price", "Units_Sold", "Rating"]
df_norm = (df[cols]- df[cols].min()) / (df[cols].max() - df[cols].min())
display(df_norm)

       Price  Units_Sold    Rating
0   0.020243    0.518519  0.428571
1   0.048583    0.277778  0.714286
2   0.016194    0.203704  0.142857
3   0.089069    0.629630  0.857143
4   0.149798    0.833333  0.571429
5   0.036437    0.592593  0.285714
6   0.024291    0.129630  0.000000
7   0.064777    0.351852  0.428571
8   0.210526    0.481481  1.000000
9   0.028340    0.222222  0.285714
10  0.311741    1.000000  0.857143
11  0.174089    0.407407  0.714286
12  0.052632    0.500000  0.571429
13  0.016194    0.092593  0.142857
14  0.024291    0.240741  0.285714
15  0.251012    0.444444  0.857143
16  0.036437    0.259259  0.428571
17  0.068826    0.648148  0.571429
18  0.109312    0.851852  0.714286
19  0.040486    0.351852  0.428571
20  0.008097    0.148148  0.000000
21  0.089069    0.444444  0.571429
22  0.352227    0.185185  0.857143
23  0.020243    0.259259  0.285714
24  0.129555    0.592593  0.714286
25  0.174089    0.166667  0.571429
26  0.514170    0.129630  1.000000
27  0.076923    0.370370  0.428571
28  0.016194    0.314815  0.285714
29  0.048583    0.351852  0.428571
30  0.392713    0.240741  0.857143
31  0.230769    0.203704  0.714286
32  0.129555    0.666667  0.571429
33  0.473684    0.092593  0.857143
34  0.635628    0.037037  1.000000
35  0.012146    0.166667  0.142857
36  0.020243    0.462963  0.285714
37  0.000000    0.574074  0.000000
38  0.028340    0.259259  0.428571
39  0.048583    0.111111  0.571429
40  0.109312    0.148148  0.714286
41  0.433198    0.074074  0.857143
42  0.190283    0.351852  0.571429
43  1.000000    0.000000  1.000000
44  0.068826    0.444444  0.428571
45  0.311741    0.240741  0.857143
46  0.757085    0.092593  0.714286
47  0.089069    0.185185  0.571429
48  0.129555    0.148148  0.428571
49  0.028340    0.314815  0.285714

In [ ]:
# Z-score normalisation
df["Units_Zscore"] = (df["Units_Sold"] - df["Units_Sold"].mean())/ df["Units_Sold"].std()
display(df[['Product_Name', 'Units_Sold', 'Units_Zscore']])

                   Product_Name  Units_Sold  Units_Zscore
0                Wireless Mouse         350      0.812282
1             Bluetooth Speaker         220     -0.260855
2                  USB Keyboard         180     -0.591051
3                Gaming Headset         410      1.307576
4                    Smartwatch         520      2.215615
5                    Power Bank         390      1.142478
6                  Laptop Stand         140     -0.921247
7                        Webcam         260      0.069341
8                  Portable SSD         330      0.647184
9              Wireless Charger         190     -0.508502
10  Noise Cancelling Headphones         610      2.958556
11          Mechanical Keyboard         290      0.316988
12                 Gaming Mouse         340      0.729733
13                 Tablet Stand         120     -1.086345
14                      USB Hub         200     -0.425953
15          External Hard Drive         310      0.482086
16            Smartphone Tripod         210     -0.343404
17              Laptop Backpack         420      1.390125
18            Bluetooth Earbuds         530      2.298164
19                LED Desk Lamp         260      0.069341
20                 Phone Holder         150     -0.838698
21            Wireless Keyboard         310      0.482086
22             Portable Monitor         170     -0.673600
23                   Smart Plug         210     -0.343404
24                  WiFi Router         390      1.142478
25              Graphics Tablet         160     -0.756149
26                   VR Headset         140     -0.921247
27                   Microphone         270      0.151890
28             Smart Light Bulb         240     -0.095757
29           Laptop Cooling Pad         260      0.069341
30                Action Camera         200     -0.425953
31               Smart Doorbell         180     -0.591051
32              Streaming Stick         430      1.472674
33           Portable Projector         120     -1.086345
34                 Gaming Chair          90     -1.333992
35               Desk Organizer         160     -0.756149
36              USB Flash Drive         320      0.564635
37       Phone Screen Protector         380      1.059929
38                Laptop Sleeve         210     -0.343404
39           Wireless Presenter         130     -1.003796
40         Tablet Keyboard Case         150     -0.838698
41             Smart Thermostat         110     -1.168894
42              Security Camera         260      0.069341
43                 Drone Camera          70     -1.499090
44              Electric Kettle         310      0.482086
45                    Air Fryer         200     -0.425953
46                 Robot Vacuum         120     -1.086345
47                  Smart Scale         170     -0.673600
48          Digital Photo Frame         150     -0.838698
49                 Portable Fan         240     -0.095757

In [ ]:
# Decimal Scaling (reviews and price)
df["Reviews_Scaled"] = df["Reviews"] / 1000
df["Price_Scaled"]= df["Price"]/100000
display(df[['Product_Name', 'Reviews', 'Reviews_Scaled','Price', 'Price_Scaled']])

                   Product_Name  Reviews  Reviews_Scaled  Price  Price_Scaled
0                Wireless Mouse     1520            1.52    799       0.00799
1             Bluetooth Speaker      980            0.98   1499       0.01499
2                  USB Keyboard      870            0.87    699       0.00699
3                Gaming Headset     2100            2.10   2499       0.02499
4                    Smartwatch     3050            3.05   3999       0.03999
5                    Power Bank     1750            1.75   1199       0.01199
6                  Laptop Stand      620            0.62    899       0.00899
7                        Webcam     1120            1.12   1899       0.01899
8                  Portable SSD     1850            1.85   5499       0.05499
9              Wireless Charger      760            0.76    999       0.00999
10  Noise Cancelling Headphones     4200            4.20   7999       0.07999
11          Mechanical Keyboard     2100            2.10   4599       0.04599
12                 Gaming Mouse     1300            1.30   1599       0.01599
13                 Tablet Stand      540            0.54    699       0.00699
14                      USB Hub      870            0.87    899       0.00899
15          External Hard Drive     2300            2.30   6499       0.06499
16            Smartphone Tripod      760            0.76   1199       0.01199
17              Laptop Backpack     1600            1.60   1999       0.01999
18            Bluetooth Earbuds     3500            3.50   2999       0.02999
19                LED Desk Lamp      980            0.98   1299       0.01299
20                 Phone Holder      420            0.42    499       0.00499
21            Wireless Keyboard     1450            1.45   2499       0.02499
22             Portable Monitor     1250            1.25   8999       0.08999
23                   Smart Plug      720            0.72    799       0.00799
24                  WiFi Router     2100            2.10   3499       0.03499
25              Graphics Tablet      980            0.98   4599       0.04599
26                   VR Headset     3100            3.10  12999       0.12999
27                   Microphone     1300            1.30   2199       0.02199
28             Smart Light Bulb      880            0.88    699       0.00699
29           Laptop Cooling Pad      990            0.99   1499       0.01499
30                Action Camera     2100            2.10   9999       0.09999
31               Smart Doorbell     1750            1.75   5999       0.05999
32              Streaming Stick     2500            2.50   3499       0.03499
33           Portable Projector     1450            1.45  11999       0.11999
34                 Gaming Chair     2100            2.10  15999       0.15999
35               Desk Organizer      450            0.45    599       0.00599
36              USB Flash Drive      900            0.90    799       0.00799
37       Phone Screen Protector      600            0.60    299       0.00299
38                Laptop Sleeve      720            0.72    999       0.00999
39           Wireless Presenter      520            0.52   1499       0.01499
40         Tablet Keyboard Case      850            0.85   2999       0.02999
41             Smart Thermostat     1200            1.20  10999       0.10999
42              Security Camera     2100            2.10   4999       0.04999
43                 Drone Camera     1800            1.80  24999       0.24999
44              Electric Kettle     1400            1.40   1999       0.01999
45                    Air Fryer     2200            2.20   7999       0.07999
46                 Robot Vacuum     1650            1.65  18999       0.18999
47                  Smart Scale      980            0.98   2499       0.02499
48          Digital Photo Frame      870            0.87   3499       0.03499
49                 Portable Fan      760            0.76    999       0.00999

In [ ]:
# Turning categorical Variables into quantitative variables
import pandas as pd
df = pd.read_csv("/content/Student-Dataset.csv")
display(df)

,Roll_No,Gender,Department,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary
0,101,Female,Computer,8.2,0,92,Placed,450000
1,102,Male,IT,7.5,1,85,Not Placed,0
2,103,Female,ENTC,9.1,0,96,Placed,550000
3,104,Male,Mechanical,6.8,2,78,Not Placed,0
4,105,Female,Computer,8.7,0,88,Placed,480000
5,106,Male,Civil,7.2,3,72,Not Placed,0
6,107,Female,IT,8.9,0,91,Placed,500000
7,108,Male,Computer,6.5,1,80,Not Placed,0
8,109,Female,ENTC,7.8,0,84,Placed,420000
9,110,Male,Mechanical,7.0,2,76,Not Placed,0

In [ ]:
# label enoding placement status
#Method 1:Label Encoding
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Placement_Status']=le.fit_transform(df['Placement_Status'])
df

,Roll_No,Gender,Department,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary
0,101,Female,Computer,8.2,0,92,1,450000
1,102,Male,IT,7.5,1,85,0,0
2,103,Female,ENTC,9.1,0,96,1,550000
3,104,Male,Mechanical,6.8,2,78,0,0
4,105,Female,Computer,8.7,0,88,1,480000
5,106,Male,Civil,7.2,3,72,0,0
6,107,Female,IT,8.9,0,91,1,500000
7,108,Male,Computer,6.5,1,80,0,0
8,109,Female,ENTC,7.8,0,84,1,420000
9,110,Male,Mechanical,7.0,2,76,0,0

In [ ]:
#Method 2:# one hot encoding placement status
df_encoded=pd.get_dummies(df,columns=['Placement_Status'])
display(df_encoded)

,Roll_No,Gender,Department,CGPA,Number_of_Backlogs,Attendance_Percentage,Salary,Placement_Status_0,Placement_Status_1
0,101,Female,Computer,8.2,0,92,450000,False,True
1,102,Male,IT,7.5,1,85,0,True,False
2,103,Female,ENTC,9.1,0,96,550000,False,True
3,104,Male,Mechanical,6.8,2,78,0,True,False
4,105,Female,Computer,8.7,0,88,480000,False,True
5,106,Male,Civil,7.2,3,72,0,True,False
6,107,Female,IT,8.9,0,91,500000,False,True
7,108,Male,Computer,6.5,1,80,0,True,False
8,109,Female,ENTC,7.8,0,84,420000,False,True
9,110,Male,Mechanical,7.0,2,76,0,True,False

In [ ]:
#Method3:Dummy Encoding (department)
df_encoded=pd.get_dummies(df,columns=['Department'],drop_first=True)
print(df_encoded)

   Roll_No  Gender  CGPA  Number_of_Backlogs  Attendance_Percentage  \
0      101  Female   8.2                   0                     92
1      102    Male   7.5                   1                     85
2      103  Female   9.1                   0                     96
3      104    Male   6.8                   2                     78
4      105  Female   8.7                   0                     88
5      106    Male   7.2                   3                     72
6      107  Female   8.9                   0                     91
7      108    Male   6.5                   1                     80
8      109  Female   7.8                   0                     84
9      110    Male   7.0                   2                     76

   Placement_Status  Salary  Department_Computer  Department_ENTC  \
0                 1  450000                 True            False
1                 0       0                False            False
2                 1  550000                False             True
3                 0       0                False            False
4                 1  480000                 True            False
5                 0       0                False            False
6                 1  500000                False            False
7                 0       0                 True            False
8                 1  420000                False             True
9                 0       0                False            False

   Department_IT  Department_Mechanical
0          False                  False
1           True                  False
2          False                  False
3          False                   True
4          False                  False
5          False                  False
6           True                  False
7          False                  False
8          False                  False
9          False                   True